### ISSUE TITLE
Build failure with PHP 7.3

### ISSUE THREAD

**Issue by cmb69** [krakjoe/uopz#79]
Trying to build current uopz master with current PHP master or PHP-7.3.0alpha3 results in compile failures. Firstly, [this `GC_REFCOUNT`](https://github.com/krakjoe/uopz/blob/90a619d5e92d0b510ffcd069a54fdc4e510f7fe4/src/function.c#L280) has to be replaced by `GC_ADDREF(entry->op_array.static_variables);`. Secondly, all occurences of `EX_CONSTANT` also need [updates](https://github.com/php/php-src/blob/d798fd491be77943fb751ad97d85475bf324192c/UPGRADING.INTERNALS#L40-L55).

[This patch](https://gist.github.com/cmb69/3060a552fc825497d066262ab31f3998) appears to solve the issue for PHP 7.3 only. I still get 3 failing tests (plus 2 borked ones), though. I'll try to investigate further.

**Comment by cmb69** [comment]
See also https://externals.io/message/102623.

**Comment by Jan-E** [comment]
@cmb69 
Even with this patch php_uopz.dll now fails to compile in PHP 7.3.0 beta 1:
```
ext\uopz\src\constant.c(60): error C2039: 'flags': is not a member of '_zend_constant'
ext\uopz\src\constant.c(62): error C2039: 'module_number': is not a member of '_zend_constant'
ext\uopz\src\constant.c(83): error C2039: 'module_number': is not a member of '_zend_constant'
ext\uopz\src\constant.c(115): error C2039: 'module_number': is not a member of '_zend_constant'
```
Apparently something changed between alpha4 and beta1. Error lines starting here:
https://github.com/krakjoe/uopz/blob/master/src/constant.c#L60

**Comment by krakjoe** [comment]
We are working with 7.3 now ... tentatively ... only in head ...

**Comment by deguif** [comment]
Is a new release on `pecl` planned?

**Comment by deguif** [comment]
Perfect, thanks, I can't wait to support PHP 7.3 on our testing tools ;)
