### ISSUE TITLE
Build fails with PHP 8.4

### ISSUE THREAD

**Issue by petk** [krakjoe/uopz#184]
On PHP 8.4 the [exit() RFC](https://github.com/php/php-src/pull/13483) was implemented and the uopz needs to be adjusted.

```
phpize
./configure
make
```

Produces:

```
/uopz/src/handlers.c:127:20: error: 'ZEND_EXIT' undeclared here (not in a function); did you mean 'ZEND_CAST'?
  127 |  UOPZ_HANDLER_DECL(ZEND_EXIT,     exit)
      |                    ^~~~~~~~~
/uopz/src/handlers.c:81:35: note: in definition of macro 'UOPZ_HANDLER_DECL'
   81 | #define UOPZ_HANDLER_DECL(o, n)  {o, &zend_vm_##n, uopz_vm_##n},
      |                                   ^
make: *** [Makefile:215: src/handlers.lo] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by cmb69** [comment]
For what it's worth, see https://news-web.php.net/php.internals/124783, which has some hints on how to keep uopz compatible with PHP 8.4.

**Comment by zonuexe** [comment]
For those looking for a quick way to build uopz with PHP 8.4:

Applying [this patch](https://github.com/krakjoe/uopz/commit/b2791e062fa94496dba13e4607e4738a7ae9b17f.patch) https://github.com/krakjoe/uopz/commit/b2791e062fa94496dba13e4607e4738a7ae9b17f will make it possible to build, but `exit()` will always be enabled and will not be affected by `uopz_allow_exit()` and `ini(uopz.exit)`.

**Comment by zonuexe** [comment]
In my opinion, it would be easier for uopz to declare that the `exit` feature is not supported for PHP 8.4 and have users who need it configure the following code:

```php
uopz_add_function('exit', function () {});
```

**Comment by cmb69** [comment]
It seems to me that #185 is a nice solution. It works with PHP 8.4 like it worked before, but still users can use `uopz_set_return()` to mock `exit()` calls.

**Comment by Jan-E** [comment]
@krakjoe Glad to see that you found the energy to get this done.
